// Generated by apigen cli from backend/openapi.json — do not edit by hand.
// Every feature route as `api <area> <action>`; the call goes through callRoute
// (cli/src/lib/apigen-call.ts), which uses this CLI's own sign-in and client, and bad
// input through failRoute (the CLI's own error output).
import { Command } from 'commander';
import { callRoute, failRoute } from '../lib/apigen-call.js';

type Kind = 'string' | 'number' | 'boolean' | 'array' | 'json';
interface Field { name: string; kind: Kind; required: boolean; choices?: string[] }
interface Route { name: string; method: string; path: string; summary: string; pathParams: string[]; query: Field[]; body: Field[] | null }

export const API_ROUTES: Array<{ area: string; routes: Route[] }> = [
 {
  "area": "access-keys",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/access-keys",
    "summary": "An access key = a MachineIdentity + one MachineToken, created together.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     },
     {
      "name": "expiresInDays",
      "kind": "number",
      "required": false
     }
    ]
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/access-keys",
    "summary": "List access keys",
    "pathParams": [],
    "query": [],
    "body": null
   },
   {
    "name": "revoke",
    "method": "POST",
    "path": "/api/v1/access-keys/{id}/revoke",
    "summary": "Revoke an access key",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "audit",
  "routes": [
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/audit",
    "summary": "List audit",
    "pathParams": [],
    "query": [
     {
      "name": "limit",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "environments",
  "routes": [
   {
    "name": "secrets",
    "method": "GET",
    "path": "/api/v1/environments/{envId}/secrets",
    "summary": "List secrets",
    "pathParams": [
     "envId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "set-secrets",
    "method": "PUT",
    "path": "/api/v1/environments/{envId}/secrets",
    "summary": "PUT = create-or-rotate (writes a new immutable version).",
    "pathParams": [
     "envId"
    ],
    "query": [],
    "body": [
     {
      "name": "key",
      "kind": "string",
      "required": true
     },
     {
      "name": "value",
      "kind": "string",
      "required": true
     }
    ]
   }
  ]
 },
 {
  "area": "projects",
  "routes": [
   {
    "name": "by-slug",
    "method": "GET",
    "path": "/api/v1/projects/by-slug/{projectSlug}",
    "summary": "Get a by slug",
    "pathParams": [
     "projectSlug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "by-slug-environments",
    "method": "GET",
    "path": "/api/v1/projects/by-slug/{projectSlug}/environments/{envSlug}",
    "summary": "Get an environment",
    "pathParams": [
     "projectSlug",
     "envSlug"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/projects",
    "summary": "RequireAuth is attached PER-ROUTE (not r.use) so unmatched paths fall through to the parent 404 handler instead of 401.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "create-environments",
    "method": "POST",
    "path": "/api/v1/projects/{projectId}/environments",
    "summary": "Environments a project",
    "pathParams": [
     "projectId"
    ],
    "query": [],
    "body": [
     {
      "name": "name",
      "kind": "string",
      "required": true
     }
    ]
   },
   {
    "name": "environments",
    "method": "GET",
    "path": "/api/v1/projects/{projectId}/environments",
    "summary": "List environments",
    "pathParams": [
     "projectId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/projects",
    "summary": "List projects",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 },
 {
  "area": "reveal",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/reveal",
    "summary": "POST (audited, off GET so the value never hits logs/URLs), rate-limited like the id-based reveal.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "path",
      "kind": "string",
      "required": true
     },
     {
      "name": "version",
      "kind": "number",
      "required": false
     }
    ]
   }
  ]
 },
 {
  "area": "search",
  "routes": [
   {
    "name": "secrets",
    "method": "GET",
    "path": "/api/v1/search/secrets",
    "summary": "List secrets",
    "pathParams": [],
    "query": [
     {
      "name": "q",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "secrets",
  "routes": [
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/secrets/{secretId}",
    "summary": "Delete a secret",
    "pathParams": [
     "secretId"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "reveal",
    "method": "POST",
    "path": "/api/v1/secrets/{secretId}/reveal",
    "summary": "Reveal is a POST (not GET) — it's a state-ish, always-audited action; keeping it off GET avoids the value ever landing in access logs / URLs.",
    "pathParams": [
     "secretId"
    ],
    "query": [
     {
      "name": "version",
      "kind": "number",
      "required": false
     }
    ],
    "body": null
   }
  ]
 },
 {
  "area": "webhooks",
  "routes": [
   {
    "name": "create",
    "method": "POST",
    "path": "/api/v1/webhooks",
    "summary": "RequireAuth is attached PER-ROUTE (not r.use) so unmatched paths fall through to the parent 404 handler instead of 401.",
    "pathParams": [],
    "query": [],
    "body": [
     {
      "name": "url",
      "kind": "string",
      "required": true
     },
     {
      "name": "events",
      "kind": "array",
      "required": true
     },
     {
      "name": "description",
      "kind": "string",
      "required": false
     }
    ]
   },
   {
    "name": "delete",
    "method": "DELETE",
    "path": "/api/v1/webhooks/{id}",
    "summary": "Delete a webhook",
    "pathParams": [
     "id"
    ],
    "query": [],
    "body": null
   },
   {
    "name": "deliveries",
    "method": "GET",
    "path": "/api/v1/webhooks/{id}/deliveries",
    "summary": "List deliveries",
    "pathParams": [
     "id"
    ],
    "query": [
     {
      "name": "limit",
      "kind": "string",
      "required": false
     }
    ],
    "body": null
   },
   {
    "name": "list",
    "method": "GET",
    "path": "/api/v1/webhooks",
    "summary": "List webhooks",
    "pathParams": [],
    "query": [],
    "body": null
   }
  ]
 }
];

// A field whose flag would clash with this command's own options or the CLI's global ones
// is given as --field-<name>.
const RESERVED = new Set(['help', 'version', 'json', 'profile', 'api', 'on-behalf-of', 'color', 'no-color', 'body-json']);
const plain = (name: string): string => name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/_/g, '-').toLowerCase();
const flag = (name: string): string => (RESERVED.has(plain(name)) ? `field-${plain(name)}` : plain(name));
const camel = (name: string): string => flag(name).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function value(field: Field, raw: string): unknown {
  if (field.kind === 'number') {
    const n = Number(raw);
    if (Number.isNaN(n)) throw new Error(`--${flag(field.name)} must be a number`);
    return n;
  }
  if (field.kind === 'boolean') return raw === '' || raw === 'true' || raw === '1' || raw === 'yes';
  if (field.kind === 'array') return raw.trim().startsWith('[') ? JSON.parse(raw) : raw.split(',').map((x) => x.trim()).filter(Boolean);
  if (field.kind === 'json') return JSON.parse(raw);
  if (field.choices && !field.choices.includes(raw)) throw new Error(`--${flag(field.name)} must be one of: ${field.choices.join(', ')}`);
  return raw;
}

export function buildApiCommand(): Command {
  const api = new Command('api').description('Every route of the API, one command each (generated from the API spec)');
  for (const { area, routes } of API_ROUTES) {
    const group = new Command(area).description(`${area} routes`);
    for (const route of routes) {
      const cmd = new Command(route.name).description(`${route.summary} (${route.method} ${route.path})`);
      for (const p of route.pathParams) cmd.argument(`<${p}>`);
      const fields = [...route.query, ...(route.body ?? [])];
      for (const f of fields) {
        const hint = f.choices ? ` (${f.choices.join('|')})` : f.kind === 'json' || f.kind === 'array' ? ` (${f.kind})` : '';
        cmd.option(f.kind === 'boolean' ? `--${flag(f.name)} [value]` : `--${flag(f.name)} <value>`, `${f.required ? 'required' : 'optional'}${hint}`);
      }
      if (route.body) cmd.option('--body-json <json>', 'the whole body as JSON (fields given as flags override it)');
      cmd.action(async (...parts: unknown[]) => {
        const command = parts[parts.length - 1] as Command;
        const opts = command.opts() as Record<string, string | boolean | undefined>;
        try {
        let path = route.path;
        route.pathParams.forEach((p, i) => { path = path.replace(`{${p}}`, encodeURIComponent(String(parts[i]))); });
        const query: Record<string, unknown> = {};
        for (const f of route.query) {
          const raw = opts[camel(f.name)];
          if (raw !== undefined) query[f.name] = value(f, raw === true ? '' : String(raw));
        }
        let body: Record<string, unknown> | undefined;
        if (route.body) {
          body = opts.bodyJson ? (JSON.parse(String(opts.bodyJson)) as Record<string, unknown>) : {};
          for (const f of route.body) {
            const raw = opts[camel(f.name)];
            if (raw !== undefined) body[f.name] = value(f, raw === true ? '' : String(raw));
          }
          const missing = route.body.filter((f) => f.required && body![f.name] === undefined).map((f) => `--${flag(f.name)}`);
          if (missing.length) throw new Error(`missing ${missing.join(', ')}`);
        }
        await callRoute(command, route.method, path, query, body);
        } catch (err) {
          await failRoute(command, err);
        }
      });
      group.addCommand(cmd);
    }
    api.addCommand(group);
  }
  return api;
}
